### ISSUE TITLE
Upload package to brew

### ISSUE THREAD

**Issue by BetterB0y** [Gaulomatic/AirPodsSanity#7]
Did you thought about uploading package to brew?

**Comment by Gaulomatic** [comment]
I just flew over the documentation on how to add an app to HomeBrew. Since I prefer MacPorts over HomeBrew, I am already confused by their terminology. It seems like they brew too much of something that should not be drank 🤭 I will consider it when I have the mental stretchiness to translate their terms to concepts I understand. This is me being hampered by my mental picture of how things could be named.

**Comment by noizo** [comment]
I just used chat gpt for some instructions, doesn't look that hard.
Btw, would never thought of using MacPorts in 2024, thought brew is a standard now.
Some steps obviously not needed since you already have built app.

# How to Prepare a Homebrew Cask for AirPodsSanity

This guide walks you through creating a Homebrew **cask** for [AirPodsSanity](https://github.com/Gaulomatic/AirPodsSanity), so it can be installed via:

```bash
brew install --cask airpods-sanity
```

---

## 1. Prerequisites

- macOS with Homebrew installed
- A GitHub repo to host your custom tap (e.g., `yourname/homebrew-tap`)
- The AirPodsSanity `.app` built and exported from Xcode
- `.dmg` or `.zip` installer archive containing the `.app` bundle

---

## 2. Build and Package AirPodsSanity

1. Clone the project:

   ```bash
   git clone https://github.com/Gaulomatic/AirPodsSanity.git
   cd AirPodsSanity
   ```

2. Open the project in Xcode and build it for **Release**.
3. Export the `.app` bundle (found in `~/Library/Developer/Xcode/DerivedData/...`) to a folder.
4. Create a ZIP archive:

   ```bash
   cd path/to/exported/AirPodsSanity.app
   cd ..
   zip -r AirPodsSanity.zip AirPodsSanity.app
   ```

5. Upload `AirPodsSanity.zip` to a public URL (e.g., GitHub Release or your own server).

---

## 3. Create a Homebrew Tap (if not already)

```bash
mkdir -p ~/homebrew-airpods/Formula
cd ~/homebrew-airpods
git init
gh repo create yourname/homebrew-airpods --public
git remote add origin git@github.com:yourname/homebrew-airpods.git
```

---

## 4. Create the Cask File

Create this file:

```bash
mkdir -p Casks
touch Casks/airpods-sanity.rb
```

Add this content to `Casks/airpods-sanity.rb`:

```ruby
cask "airpods-sanity" do
  version "1.5.0"
  sha256 "<SHA256 of AirPodsSanity.zip>"

  url "https://github.com/Gaulomatic/AirPodsSanity/releases/download/v1.5.0/AirPodsSanity.zip",
      verified: "github.com/Gaulomatic/AirPodsSanity/"
  name "AirPodsSanity"
  desc "Fixes annoying macOS AirPods behavior"
  homepage "https://github.com/Gaulomatic/AirPodsSanity"

  app "AirPodsSanity.app"

  zap trash: [
    "~/Library/Preferences/com.Gaulomatic.AirPodsSanity.plist",
    "~/Library/Application Support/AirPodsSanity",
  ]
end
```

To get the SHA:

```bash
shasum -a 256 AirPodsSanity.zip
```

---

## 5. Commit and Push

```bash
git add .
git commit -m "Add AirPodsSanity cask"
git push -u origin main
```

---

## 6. Install from Your Tap

Now users can install it using:

```bash
brew tap yourname/airpods
brew install --cask airpods-sanity
```

---

## Optional: Submit to Homebrew Core Casks

Once stable and if widely useful, submit the cask to the official Homebrew repository:

- Fork: https://github.com/Homebrew/homebrew-cask
- Add your cask under `Casks/airpods-sanity.rb`
- Submit a PR per [Homebrew Cask Contribution Guide](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md)

And for updating cask:

```yaml
name: Update Homebrew Cask

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 02:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-cask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Dependencies
        run: |
          brew install homebrew/cask-repair
          brew tap homebrew/cask

      - name: Update Cask
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cask_name="airpods-sanity"

          # Fetch latest GitHub release version
          latest_version=$(curl --silent "https://api.github.com/repos/Gaulomatic/AirPodsSanity/releases/latest" | jq -r .tag_name)

          # Extract current version from cask
          current_version=$(brew info --cask $cask_name --json | jq -r '.[0].version')

          echo "Latest: $latest_version, Current: $current_version"

          if [[ "$latest_version" == "null" ]] || [[ -z "$latest_version" ]]; then
            echo "Failed to fetch latest version."
            exit 1
          fi

          if [[ "$latest_version" != "$current_version" ]]; then
            echo "New version detected. Updating..."
            cask-repair --cask $cask_name --version $latest_version --pull --no-browse
          else
            echo "No update needed."
          fi
```
### How It Works
	1.	Runs every day at 02:00 UTC (cron: '0 2 * * *').
	2.	Manually triggerable from GitHub Actions (workflow_dispatch).
	3.	Checks the latest GitHub release version for AirPodsSanity.
	4.	Compares it with the installed Homebrew cask version.
	5.	If a new version is found, it:
	  •	Updates the cask.
	  •	Opens a pull request (PR) automatically.
	6.	Uses GitHub’s built-in token (secrets.GITHUB_TOKEN) for authentication.

### Setup Instructions
	1.	Add this workflow to your Homebrew tap repository under:
```
.github/workflows/update-cask.yml
```
	2.	Ensure your tap repository is public (so Homebrew can fetch it).
	3.	Allow GitHub Actions to create pull requests (enabled by default).
	4.	Run the workflow manually once (to test).
	  •	Go to GitHub → Actions → Update Homebrew Cask → Click Run workflow.

### What Happens After a New Release?
	1.	GitHub Action detects the update.
	2.	It automatically updates the Casks/airpods-sanity.rb file.
	3.	A pull request (PR) is created in your tap repo.
	4.	You or Homebrew maintainers review & merge.
	5.	Users update by running:
```bash
brew update
brew upgrade --cask airpods-sanity
```
